const db = {
  apple: { hindiWord: ['सेब'] },
  banana: { hindiWord: ['केला'] },
  apricot: { hindiWord: ['खुबानी'] },  
  pomegranate: { hindiWord: ['अनार']},
  mango: { hindiWord: ['आम']},
  lemon: { hindiWord: ['नींबू']},
  orange: { hindiWord: ['संतरा']},
  pineapple: { hindiWord: ['अनानास']},
  grapes: { hindiWord: ['अंगूर']},
  watermelon: { hindiWord: ['तरबूज'] },
  papaya: { hindiWord: ['पपीता']},
  blackberry: { hindiWord: [' जामुन'] },
  peach: { hindiWord: ['आड़ू'] },
  pear: { hindiWord: ['नाशपाती']},
  jujube: { hindiWord: ['बेर'] },
  custardapple: { hindiWord: ['सीताफल'] },
  raspberry: { hindiWord: ['रसभरी'] },
  starfruit: { hindiWord: ['कमरख'] },
  sugarcane: { hindiWord: ['गन्ना']},
  mulberry: { hindiWord: ['शहतूत']},
  guava:{hindiWord:['अमरुद']},

  capsicum: { hindiWord: ['शिमला मिर्च'] },
  carrot: { hindiWord: ['गाजर'] },
  cauliflower: { hindiWord: ['फूल गोभी'] },
  corn: { hindiWord: ['मक्का'] },
  clusterbeans: { hindiWord: ['गवार फली']},
  mushroom: { hindiWord: ['कुकुरमुत्ता']},
  onion: { hindiWord: ['प्याज']},
  peas: { hindiWord: ['मटर']},
  potato: { hindiWord: ['आलू']},
  spinach: { hindiWord: ['पालक'] },
  sweetpotato: { hindiWord: ['शकर कन्द'] },
  pumpkin: { hindiWord: ['कद्दू ']} ,
  bottlegourd: {hindiWord:['लौकी'] },
  bittergourd:{hindiWord:['करेला'] },
  beetroot:{ hindiWord:['चकुंदर']},
  brinjal:{hindiWord:['बैगन']},
  cucumber:{hindiWord:['खीरा']},
  garbanzobeans:{hindiWord:['चना']},
  garlic:{hindiWord:['लहसुन']},
  ginger:{hindiWord:['अदरक']},
  tomato:{hindiWord:['टमाटर']},

  determination :{hindiWord:['दृढ़ निश्चय']},
  faith:{hindiWord:['श्रद्धा']},
  happiness:{hindiWord:['ख़ुशी']},
  honesty:{hindiWord:['ईमानदारी']},
  justice:{hindiWord:['न्याय']},
  kindness:{hindiWord:['दयालुता']},
  knowledge:{hindiWord:['ज्ञान']},
  love:{hindiWord:['प्रेम']},
  loyalty:{hindiWord:['निष्ठा']},
  poise:{hindiWord:['संतुलन']},
  respect:{hindiWord:['आदर']},
  responsibility:{hindiWord:['ज़िम्मेदारी']},
  selfrespect:{hindiWord:['आत्म सम्मान']},
  service:{hindiWord:['सेवा']},
  success:{hindiWord:['सफलता']},
  wisdom:{hindiWord:['बुद्धिमत्ता']},
  compassion:{hindiWord:['दया']},
  autonomy:{hindiWord:['स्वायत्तता']},
  competency:{hindiWord:['क्षमता']},
  growth:{hindiWord:['वृद्धि']},
  security:{hindiWord:['सुरक्षा']},
  discipline:{hindiWord:['अनुशासन']},

  bed:{ hindiWord:['बिस्तर, पलंग']},
  bucket:{hindiWord:['बाल्टी']},
  candle:{hindiWord:['मोमबत्ती']},
  carpet :{hindiWord:['दरी, गलीचा']},
  chair : {hindiWord:['कुर्सी']},
  comb :{hindiWord:['कंघी']},
  couch :{hindiWord:['सोफ़ा']},
  iron :{hindiWord:['इस्त्री']},
  quilt :{hindiWord:['रजाई,लिहाफ']},
  rope :{hindiWord:['रस्सी']},
  ash:{hindiWord:[' राख']},
  tabledesk :{hindiWord:['लेखनाधार']},
  pen :{hindiWord:['कलम']},
  bowl :{hindiWord:['कटोरा, डोंगा']},
  phial :{hindiWord:['शीशी']},
  box :{hindiWord:['सन्दूक']},
  fork :{hindiWord:[' कांटा']},
  spoon :{hindiWord:[' चमचा']},
  stick :{hindiWord:[' छड़ी']},
  umbrella :{hindiWord:[' छाता']},
  cup:{hindiWord:['प्याला']},
  chandelier:{hindiWord:['झूमर']},
  soap:{hindiWord:['साबुन']},
  tree:{hindiWord:['पेड़']},
  needle:{hindiWord:['सुई']},
  mortar:{hindiWord:['ओखली']},
  cauldron:{hindiWord:['कढ़ाई']},
  stairs:{hindiWord:['सीढियां']},
  pillow:{hindiWord:['तकिया']},
  table:{hindiWord:['मेज़']},

  camel:{hindiWord:['ऊंट']},
	turtle:{hindiWord:['कछुआ']},
  bitch:{hindiWord:['कुतिया']},
  dog:{hindiWord:['कुत्ता']},
  rabbit:{hindiWord:['खरगोश	']},
  donkey:{hindiWord:['गधा	']},
  cow:{hindiWord:['गाय']},
  horse:{hindiWord:['घोड़ा']},
  mouse:{hindiWord:['चूहा']},
  monkey:{hindiWord:['बंदर']},
  goat:{hindiWord:['बकरी']},
  cat:{hindiWord:['बिल्ली']},
  ox:{hindiWord:['बैल']},
  bear:{hindiWord:['भालू']},
  buffalo:{hindiWord:['भैंस']},
  fish:{hindiWord:['मछली']},
  pig:{hindiWord:['सुअर']},
  elephant:{hindiWord:['हाथी']},
  squirrel:{hindiWord:['गिलहरी']},
  mole:{hindiWord:['छछूंदर']},
  panther:{hindiWord:['तेंदुआ']},
  tiger:{hindiWord:['बाघ']},
  fox:{hindiWord:['लोमड़ी']},
  deer:{hindiWord:['हिरण']},
  wolf:{hindiWord:['भेड़िया']},
  crocodile:{hindiWord:['मगरमच्छ']},
  frog:{hindiWord:['मेंढक']},
  lion:{hindiWord:['शेर']},

  addition:{hindiWord:['जोड़']},
subtraction:{hindiWord:['घटाना']},	  
multiplication:{hindiWord:['गुणन']} ,
division:{hindiWord:['विभाजन']},
fraction:{hindiWord:['भिन्‍न']},
decimal:{hindiWord:['दशमलव']},
algebra:{hindiWord:['बीजगणित']},
circle:{hindiWord:['वृत्त']},
rectangle:{hindiWord:['आयत']},
square:{hindiWord:['वर्ग']},
triangle:{hindiWord:['त्रिकोण']},	
hexagon:{hindiWord:['ष‌ट्भुज']},
pentagon:{hindiWord:['पंचभुज']},  	  
tetragon:{hindiWord:['चतुर्भुज']},  
heptagon:{hindiWord:['सप्तभुज']},  	
polygon:{hindiWord:['बहुभुज']},
quadrilateral:{hindiWord:['चतुर्भुज']},
sphere:{hindiWord:['गोला']}, 	 
cube:{hindiWord:['घन, ghan']},  	 
cuboid:{hindiWord:['घनाभ']}, 
cone:{hindiWord:['शंकु']},
factor:{hindiWord:['गुणनखंड']},
area:{hindiWord:['क्षेत्र']},
perimeter:{hindiWord:['परिमाप']},
length:{hindiWord:['लंबाई']},
width:{hindiWord:['चौड़ाई ']},
breadth:{hindiWord:['चौड़ाई']},
height:{hindiWord:['ऊंचाई']},

absolute:{hindiWord:['पूर्ण']},
advance:{hindiWord:['उन्नत']},
angle:{hindiWord:['कोण']},
brain:{hindiWord:['मस्तिष्क']},
calculate:{hindiWord:['गणना']},
dissolve:{hindiWord:['भंग']},	
examination:{hindiWord:['परीक्षा']},
mass:{hindiWord:['वजन,	Vajan']},
precipitation:{hindiWord:['वर्षा']},	
rocket:{hindiWord:['राकेट']},	
species:{hindiWord:['जाति']},
substance:{hindiWord:['पदार्थ']},
absorb:{hindiWord:['अवशोषित']},
atmosphere:{hindiWord:['वायु-मंडल']},
bolt:{hindiWord:['गाज']},
classification:{hindiWord:['वर्गीकरण']},
experiment:{hindiWord:['परीक्षण']},
explore:{hindiWord:['खोजना']},
measurement:{hindiWord:['माप']},
planet:{hindiWord:['ग्रह']},
quantity:{hindiWord:['मात्रा']},
matter:{hindiWord:['पदार्थ']},
motion:{hindiWord:['गति']},

};
export default db;